import { v3 } from '@/core/math/Vec3';
import type { MaterialAsset } from '@/core/document/types';

export type MaterialPreset = {
  id: string;
  label: string;
  category: 'general' | 'metal' | 'glass' | 'organic' | 'stylized';
  patch: Partial<Omit<MaterialAsset, 'id' | 'name'>>;
};

export const MATERIAL_PRESETS: MaterialPreset[] = [
  {
    id: 'default',
    label: 'Default',
    category: 'general',
    patch: {
      presetId: 'default',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.75, 0.75, 0.78),
      roughness: 0.6,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      alphaCutoff: 0.5,
      transmission: 0,
      ior: 1.5,
      clearcoat: 0,
      clearcoatRoughness: 0.03,
      doubleSided: false,
      flatShaded: true,
    },
  },
  {
    id: 'plastic-glossy',
    label: 'Plastic · Glossy',
    category: 'general',
    patch: {
      presetId: 'plastic-glossy',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.82, 0.18, 0.14),
      roughness: 0.22,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.35,
      clearcoatRoughness: 0.08,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'plastic-matte',
    label: 'Plastic · Matte',
    category: 'general',
    patch: {
      presetId: 'plastic-matte',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.72, 0.74, 0.78),
      roughness: 0.82,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'metal-brushed',
    label: 'Metal · Brushed',
    category: 'metal',
    patch: {
      presetId: 'metal-brushed',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.78, 0.78, 0.8),
      roughness: 0.38,
      metallic: 1,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.12,
      clearcoatRoughness: 0.15,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'metal-chrome',
    label: 'Metal · Chrome',
    category: 'metal',
    patch: {
      presetId: 'metal-chrome',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.95, 0.95, 0.96),
      roughness: 0.08,
      metallic: 1,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.55,
      clearcoatRoughness: 0.04,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'metal-gold',
    label: 'Metal · Gold',
    category: 'metal',
    patch: {
      presetId: 'metal-gold',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(1, 0.766, 0.336),
      roughness: 0.28,
      metallic: 1,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.2,
      clearcoatRoughness: 0.1,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'metal-copper',
    label: 'Metal · Copper',
    category: 'metal',
    patch: {
      presetId: 'metal-copper',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.95, 0.64, 0.42),
      roughness: 0.35,
      metallic: 1,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.15,
      clearcoatRoughness: 0.12,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'metal-rust',
    label: 'Metal · Rust',
    category: 'metal',
    patch: {
      presetId: 'metal-rust',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.58, 0.28, 0.16),
      roughness: 0.88,
      metallic: 0.55,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'glass-clear',
    label: 'Glass · Clear',
    category: 'glass',
    patch: {
      presetId: 'glass-clear',
      shadingModel: 'physical',
      unlit: false,
      baseColour: v3(1, 1, 1),
      roughness: 0.04,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 0.35,
      alphaMode: 'blend',
      alphaCutoff: 0.5,
      transmission: 0.92,
      ior: 1.52,
      clearcoat: 1,
      clearcoatRoughness: 0.02,
      doubleSided: true,
      flatShaded: false,
    },
  },
  {
    id: 'glass-frosted',
    label: 'Glass · Frosted',
    category: 'glass',
    patch: {
      presetId: 'glass-frosted',
      shadingModel: 'physical',
      unlit: false,
      baseColour: v3(0.92, 0.95, 0.98),
      roughness: 0.42,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 0.55,
      alphaMode: 'blend',
      transmission: 0.78,
      ior: 1.48,
      clearcoat: 0.65,
      clearcoatRoughness: 0.18,
      doubleSided: true,
      flatShaded: false,
    },
  },
  {
    id: 'ice',
    label: 'Ice',
    category: 'glass',
    patch: {
      presetId: 'ice',
      shadingModel: 'physical',
      unlit: false,
      baseColour: v3(0.78, 0.9, 1),
      roughness: 0.12,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 0.62,
      alphaMode: 'blend',
      transmission: 0.72,
      ior: 1.31,
      clearcoat: 0.85,
      clearcoatRoughness: 0.06,
      doubleSided: true,
      flatShaded: false,
    },
  },
  {
    id: 'water',
    label: 'Water',
    category: 'glass',
    patch: {
      presetId: 'water',
      shadingModel: 'physical',
      unlit: false,
      baseColour: v3(0.18, 0.48, 0.72),
      roughness: 0.08,
      metallic: 0.22,
      emissive: v3(0.02, 0.06, 0.1),
      emissiveIntensity: 0.4,
      opacity: 0.78,
      alphaMode: 'blend',
      transmission: 0.55,
      ior: 1.33,
      clearcoat: 0.9,
      clearcoatRoughness: 0.05,
      doubleSided: true,
      flatShaded: false,
    },
  },
  {
    id: 'rubber',
    label: 'Rubber',
    category: 'organic',
    patch: {
      presetId: 'rubber',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.12, 0.12, 0.12),
      roughness: 0.92,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'leather',
    label: 'Leather',
    category: 'organic',
    patch: {
      presetId: 'leather',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.36, 0.2, 0.1),
      roughness: 0.72,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.08,
      clearcoatRoughness: 0.35,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'wood',
    label: 'Wood',
    category: 'organic',
    patch: {
      presetId: 'wood',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.55, 0.34, 0.18),
      roughness: 0.78,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.12,
      clearcoatRoughness: 0.22,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'fabric',
    label: 'Fabric',
    category: 'organic',
    patch: {
      presetId: 'fabric',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.42, 0.46, 0.58),
      roughness: 0.95,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'stone',
    label: 'Stone',
    category: 'organic',
    patch: {
      presetId: 'stone',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.52, 0.5, 0.48),
      roughness: 0.86,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'concrete',
    label: 'Concrete',
    category: 'organic',
    patch: {
      presetId: 'concrete',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.62, 0.62, 0.6),
      roughness: 0.94,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'ceramic',
    label: 'Ceramic',
    category: 'general',
    patch: {
      presetId: 'ceramic',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.92, 0.94, 0.96),
      roughness: 0.18,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.65,
      clearcoatRoughness: 0.06,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'wax',
    label: 'Wax',
    category: 'organic',
    patch: {
      presetId: 'wax',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.95, 0.88, 0.62),
      roughness: 0.48,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.25,
      clearcoatRoughness: 0.18,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'pearl',
    label: 'Pearl',
    category: 'general',
    patch: {
      presetId: 'pearl',
      shadingModel: 'physical',
      unlit: false,
      baseColour: v3(0.96, 0.94, 0.9),
      roughness: 0.22,
      metallic: 0.08,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0.08,
      ior: 1.55,
      clearcoat: 1,
      clearcoatRoughness: 0.08,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'neon-blue',
    label: 'Neon · Blue',
    category: 'stylized',
    patch: {
      presetId: 'neon-blue',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.08, 0.18, 0.42),
      roughness: 0.35,
      metallic: 0,
      emissive: v3(0.2, 0.55, 1),
      emissiveIntensity: 2.4,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.4,
      clearcoatRoughness: 0.12,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'neon-orange',
    label: 'Neon · Orange',
    category: 'stylized',
    patch: {
      presetId: 'neon-orange',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.42, 0.14, 0.02),
      roughness: 0.35,
      metallic: 0,
      emissive: v3(1, 0.42, 0.08),
      emissiveIntensity: 2.6,
      opacity: 1,
      alphaMode: 'opaque',
      transmission: 0,
      clearcoat: 0.35,
      clearcoatRoughness: 0.12,
      doubleSided: false,
      flatShaded: false,
    },
  },
  {
    id: 'pixel-unlit',
    label: 'Pixel · Unlit',
    category: 'stylized',
    patch: {
      presetId: 'pixel-unlit',
      shadingModel: 'unlit',
      unlit: true,
      baseColour: v3(1, 1, 1),
      roughness: 1,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'mask',
      alphaCutoff: 0.5,
      transmission: 0,
      clearcoat: 0,
      doubleSided: false,
      flatShaded: true,
      textureFiltering: 'nearest',
      textureWrapping: 'clamp',
    },
  },
  {
    id: 'foliage-cutout',
    label: 'Foliage · Cutout',
    category: 'stylized',
    patch: {
      presetId: 'foliage-cutout',
      shadingModel: 'lit',
      unlit: false,
      baseColour: v3(0.28, 0.62, 0.22),
      roughness: 0.82,
      metallic: 0,
      emissive: v3(0, 0, 0),
      emissiveIntensity: 1,
      opacity: 1,
      alphaMode: 'mask',
      alphaCutoff: 0.42,
      transmission: 0,
      clearcoat: 0,
      doubleSided: true,
      flatShaded: false,
    },
  },
];

const PRESET_BY_ID = new Map(MATERIAL_PRESETS.map((preset) => [preset.id, preset]));

export function getMaterialPreset(id: string): MaterialPreset | undefined {
  return PRESET_BY_ID.get(id);
}

export function applyMaterialPreset(material: MaterialAsset, presetId: string): boolean {
  const preset = PRESET_BY_ID.get(presetId);
  if (!preset) return false;
  Object.assign(material, preset.patch);
  material.presetId = presetId;
  return true;
}

/** Fill in fields added after older projects were saved. */
export function normalizeMaterialAsset(material: MaterialAsset): MaterialAsset {
  material.presetId = material.presetId ?? null;
  material.emissiveIntensity = material.emissiveIntensity ?? 1;
  material.transmission = material.transmission ?? 0;
  material.ior = material.ior ?? 1.5;
  material.clearcoat = material.clearcoat ?? 0;
  material.clearcoatRoughness = material.clearcoatRoughness ?? 0.03;
  if (material.shadingModel !== 'lit' && material.shadingModel !== 'unlit' && material.shadingModel !== 'physical') {
    material.shadingModel = material.unlit ? 'unlit' : 'lit';
  }
  return material;
}
